export const unitData = {
  'Tercio': {
    base_cost: 140,
    speed: 4,
    melee: 4,
    shoot: [3,2],
    discipline: 5,
    courage: 4,
    stamina: 5,
    infantry:4,
    cavalry: 5,
    salvo: 4,
    artillery: 3,
    rules: ['Large'],
    weaponry: ['Pikes','Arquebus/Musket']
  },
  'Classic Squadron': {
    base_cost: 110,
    speed: 4,
    melee: 4,
    shoot: [3,2],
    discipline: 4,
    courage: 4,
    stamina: 4,
    infantry:4,
    cavalry: 5,
    salvo: 4,
    artillery: 3,
    rules: <string[]>[],
    weaponry: ['Pikes','Arquebus/Musket']
  },
  'Reformed Battalion': {
    base_cost: 125,
    speed: 4,
    melee: 4,
    shoot: [4,2],
    discipline: 4,
    courage: 4,
    stamina: 4,
    infantry:4,
    cavalry: 5,
    salvo: 4,
    artillery: 4,
    rules: ['Brigade'],
    weaponry: ['Pikes','Arquebus/Musket']
  },
  'Modern Squadron': {
    base_cost: 110,
    speed: 4,
    melee: 3,
    shoot: [4,4],
    discipline: 5,
    courage: 4,
    stamina: 3,
    infantry:4,
    cavalry: 5,
    salvo: 4,
    artillery: 4,
    rules: ['Brigade'],
    weaponry: ['Pikes','Musket']
  },
  'Cuirassiers': {
    base_cost: 100,
    speed: 7,
    melee: 4,
    shoot: [2,2],
    discipline: 3,
    courage: 4,
    stamina: 3,
    infantry:4,
    cavalry: 4,
    salvo: 3,
    artillery: 4,
    rules: ['Mobility','Evasion','Pursuit'],
    weaponry: ['Pistol']
  },
  'Mounted Arquebusier': {
    base_cost: 65,
    speed: 8,
    melee: 3,
    shoot: [3,3],
    discipline: 3,
    courage: 3,
    stamina: 3,
    infantry:4,
    cavalry: 3,
    salvo: 3,
    artillery: 4,
    rules: ['Mobility','Evasion','Pursuit','Caracole'],
    weaponry: ['Arquebus']
  },
  'Light Horse': {
    base_cost: 50,
    speed: 8,
    melee: 3,
    shoot: [2,2],
    discipline: 2,
    courage: 3,
    stamina: 2,
    infantry:4,
    cavalry: 3,
    salvo: 4,
    artillery: 5,
    rules: ['Mobility','Evasion','Pursuit','Light', 'Extended Arc of Fire'],
    weaponry: ['Pistol']
  },
  'Dragoons': {
    base_cost: 75,
    speed: 8,
    melee: 3,
    shoot: [3,3],
    discipline: 3,
    courage: 3,
    stamina: 3,
    infantry:4,
    cavalry: 3,
    salvo: 3,
    artillery: 4,
    rules: ['Mobility','Evasion','Pursuit','Dragoon', 'Light'],
    weaponry: ['Musket']
  },
  'Artillery Battery': {
    base_cost: 60,
    speed: 6,
    melee: 2,
    shoot: [1,1],
    discipline: 3,
    courage: 2,
    stamina: 1,
    infantry:3,
    cavalry: 3,
    salvo: 5,
    artillery: 5,
    rules: ['Integral Command','Crew Defence', 'No Escape'],
    weaponry: <string[]>[]
  },
};

export const companyData = {
  'Shot Company':{
    base_cost: 55,
    speed: 5,
    melee: 2,
    shoot: [3,3],
    discipline: 3,
    courage: 3,
    stamina: 2,
    infantry:3,
    cavalry: 3,
    salvo: 4,
    artillery: 4,
    rules: ['Light'],
    weaponry: ['Arquebus']
  },
  'Pike Company':{
    base_cost: 60,
    speed: 4,
    melee: 3,
    shoot: [0,0],
    discipline: 3,
    courage: 3,
    stamina: 3,
    infantry:4,
    cavalry: 5,
    salvo: 4,
    artillery: 4,
    rules: <string[]>[],
    weaponry: ['Pikes']
  },
  'Melee Company':{
    base_cost: 50,
    speed: 5,
    melee: 3,
    shoot: [0,0],
    discipline: 3,
    courage: 3,
    stamina: 3,
    infantry:4,
    cavalry: 4,
    salvo: 4,
    artillery: 4,
    rules: <string[]>[],
    weaponry: <string[]>[]
  }
};
